//! Build script for `selis-sandbox`: generates the surface budget profiles
//! from `profiles.toml` (SL-0.SBX.05).
//!
//! Generated into `$OUT_DIR/profiles.rs` as `Surface::budget()`, a const
//! function returning the [`Budget`] for each surface. The numbers live only in
//! `profiles.toml`, so tuning them cannot drift from the code.

// Build scripts fail hard by design: a missing env var or malformed TOML is a
// fatal configuration error, not a recoverable runtime condition.
#![allow(clippy::expect_used)]

use std::fmt::Write as _;

#[derive(serde::Deserialize)]
struct Profiles {
    surface: Vec<SurfaceEntry>,
}

#[derive(serde::Deserialize)]
struct SurfaceEntry {
    name: String,
    bytes: u64,
    wall: u64,
    depth: u16,
    objects: u32,
    pixels: u64,
}

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let profiles_path = std::path::Path::new(&manifest).join("profiles.toml");
    println!("cargo:rerun-if-changed={}", profiles_path.display());

    let text = std::fs::read_to_string(&profiles_path).expect("read profiles.toml");
    let profiles: Profiles = toml::from_str(&text).expect("parse profiles.toml");

    assert!(
        !profiles.surface.is_empty(),
        "profiles.toml must define at least one surface"
    );

    let mut rs = String::new();
    rs.push_str("// @generated by build.rs from profiles.toml. Do not edit.\n\n");
    rs.push_str("impl Surface {\n");
    rs.push_str("    /// The limits for this surface (SL-0.SBX.05).\n");
    rs.push_str("    #[must_use]\n");
    rs.push_str("    pub const fn budget(self) -> Budget {\n");
    rs.push_str("        match self {\n");
    for s in &profiles.surface {
        let _ = writeln!(
            rs,
            "            Surface::{} => Budget {{ bytes: {}, wall: {}, depth: {}, objects: {}, pixels: {} }},",
            s.name, s.bytes, s.wall, s.depth, s.objects, s.pixels
        );
    }
    rs.push_str("        }\n");
    rs.push_str("    }\n");
    rs.push_str("}\n");

    let out_rs = std::path::Path::new(&out_dir).join("profiles.rs");
    std::fs::write(&out_rs, rs).expect("write profiles.rs");
}
