//! Surface budget profiles (SL-0.SBX.05).
//!
//! A [`Surface`] is a *shape of work*, not a product tier — products are
//! entitlement sets (`selis-policy`, ADR-P0014), and a surface is a set of
//! resource limits chosen for one kind of operation. The same document open
//! with a `Viewer` budget is the same document open with a `Server` budget; only
//! the limits differ.
//!
//! The numbers themselves live in `profiles.toml` and are code-generated by
//! `build.rs`, so they cannot drift from their single source of truth. They are
//! starting values to be tuned against the corpus, never guessed forever.

use crate::budget::Budget;

/// The shape of work a budget is sized for.
///
/// Profiling by surface rather than by document keeps the choice mechanical:
/// `selis-policy` maps a document's provenance and the requested operation to a
/// surface, and the engine never decides its own limits.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Surface {
    /// Page-thumbnail generation and first-paint probes. Small and fast.
    Thumbnail,
    /// Opening a document for reading in a viewer. The default surface.
    Viewer,
    /// Editing operations: annotations, forms, page ops, incremental save.
    Editor,
    /// Offline batch runs (merge, split, compress, OCR) with no user waiting.
    Batch,
    /// Multi-tenant server workloads; per-document caps.
    Server,
    /// Fuzz harnesses: deliberately tiny and short.
    Fuzz,
}

impl Surface {
    /// A short stable identifier for diagnostics and logs.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Surface::Thumbnail => "thumbnail",
            Surface::Viewer => "viewer",
            Surface::Editor => "editor",
            Surface::Batch => "batch",
            Surface::Server => "server",
            Surface::Fuzz => "fuzz",
        }
    }
}

include!(concat!(env!("OUT_DIR"), "/profiles.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    /// SL-0.SBX.05 DoD: profiles are documented with the reasoning for each
    /// number — here we assert the structural invariants that keep them
    /// sensible as they are tuned:
    ///  * every limit is non-zero (no accidental "0 = unlimited" foot-gun),
    ///  * a hostile surface is strictly tighter than a friendly one,
    ///  * depth is a u16 the guard can actually enforce.
    #[test]
    fn every_profile_is_positive_and_fuzz_is_tightest() {
        for s in [
            Surface::Thumbnail,
            Surface::Viewer,
            Surface::Editor,
            Surface::Batch,
            Surface::Server,
            Surface::Fuzz,
        ] {
            let b = s.budget();
            assert!(b.bytes > 0, "{s:?}: bytes must be > 0");
            assert!(b.wall > 0, "{s:?}: wall must be > 0");
            assert!(b.depth > 0, "{s:?}: depth must be > 0");
            assert!(b.objects > 0, "{s:?}: objects must be > 0");
            assert!(b.pixels > 0, "{s:?}: pixels must be > 0");
        }
        let fuzz = Surface::Fuzz.budget();
        for s in [
            Surface::Viewer,
            Surface::Editor,
            Surface::Batch,
            Surface::Server,
        ] {
            let b = s.budget();
            assert!(fuzz.bytes < b.bytes, "fuzz bytes must be tightest");
            assert!(fuzz.wall < b.wall, "fuzz wall must be tightest");
            assert!(fuzz.depth < b.depth, "fuzz depth must be tightest");
            assert!(fuzz.objects < b.objects, "fuzz objects must be tightest");
        }
        assert_eq!(Surface::Viewer.as_str(), "viewer");
    }
}
