export {
	ErrorCode,
	AdapterError,
	type DocState,
	type ErrorCodeValue,
	isAdapterError,
} from "./errors.js";
export type {
	PlatformAdapter,
	EnginePort,
	NavigationPort,
	LocalePort,
	FilePort,
	PickOpenOptions,
	StoragePort,
	ClipboardPort,
	PrintPort,
	TelemetryPort,
	WindowPort,
} from "./adapter.js";
export type {
	Size,
	Rect,
	DocumentSourceDescriptor,
	FsaFileHandle,
	BudgetProfile,
	ProgressReport,
	AdapterRequestOptions,
	DocHandle,
	RenderTileRequest,
	RenderedTile,
	PageText,
	PageTextLayer,
	TextLayerChar,
	TextLayerLine,
	SearchOptions,
	SearchMatch,
	SearchBatch,
	PageLabelStyle,
	PageLabelRange,
	DestinationKind,
	PdfDestination,
	OutlineNode,
	NamedDestination,
	LinkActionKind,
	LinkAction,
	LinkAnnotation,
	SaveTarget,
	PrintOptions,
	TelemetryEvent,
	DeepLink,
	PlatformCapabilities,
} from "./types.js";
export {
	createMockAdapter,
	type MockAdapter,
	type MockDocumentSpec,
	type MockLinkAnnotation,
	type MockRecording,
	type PageLinkSet,
} from "./mock-adapter.js";
export { definePlatformAdapterContract, type AdapterFixture, SAMPLE_TEXTS } from "./contract.js";
