//! Build script for `selis-error`: generates the numeric code registry from
//! `codes.toml` (SL-0.ERR.01).
//!
//! Generated into `$OUT_DIR/codes.rs`:
//!   * `enum Code` — one variant per registry entry
//!   * `Code::id`, `Code::name`, `Code::kind`, `Code::doc_state`, `Code::retryable`
//!   * `Code::message_key` and `Code::user_msg_en` (SL-0.ERR.04: English is a
//!     translation of a key, not a hardcode)
//!   * `Code::from_id`
//!   * `ALL_CODES`
//!
//! Also emits `$OUT_DIR/codes.md` — the published reference (SL-0.ERR.01 DoD).

// Build scripts fail hard by design: a missing env var or malformed TOML is a
// fatal configuration error, not a recoverable runtime condition.
#![allow(clippy::expect_used)]

use std::collections::BTreeSet;
use std::fmt::Write as _;

#[derive(serde::Deserialize)]
struct Registry {
    code: Vec<Entry>,
}

#[derive(serde::Deserialize)]
struct Entry {
    id: u32,
    name: String,
    kind: String,
    meaning: String,
    user_msg: String,
    retryable: bool,
    doc_state: String,
}

const KINDS: &[&str] = &[
    "Malformed",
    "Unsupported",
    "Invalid",
    "Auth",
    "Policy",
    "Budget",
    "Cancelled",
    "Io",
    "Internal",
];

const DOC_STATES: &[&str] = &[
    "NotLoaded",
    "Loaded",
    "PartiallyLoaded",
    "Unchanged",
    "Modified",
];

fn pascal(name: &str) -> String {
    let mut out = String::new();
    for part in name.split('_') {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            out.extend(first.to_uppercase());
            out.extend(chars.flat_map(char::to_lowercase));
        }
    }
    out
}

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let codes_path = std::path::Path::new(&manifest).join("codes.toml");
    println!("cargo:rerun-if-changed={}", codes_path.display());

    let text = std::fs::read_to_string(&codes_path).expect("read codes.toml");
    let registry: Registry = toml::from_str(&text).expect("parse codes.toml");

    // --- Validation. These are the invariants `xtask check-codes` also enforces,
    // --- duplicated here so a bad registry cannot even compile.
    let mut seen_ids = BTreeSet::new();
    let mut seen_names = BTreeSet::new();
    for e in &registry.code {
        assert!(seen_ids.insert(e.id), "duplicate code id {}", e.id);
        assert!(
            seen_names.insert(e.name.clone()),
            "duplicate code name {}",
            e.name
        );
        assert!(
            KINDS.contains(&e.kind.as_str()),
            "code {} has unknown kind {:?}",
            e.id,
            e.kind
        );
        assert!(
            DOC_STATES.contains(&e.doc_state.as_str()),
            "code {} has unknown doc_state {:?}",
            e.id,
            e.doc_state
        );
        assert!(
            !e.meaning.trim().is_empty(),
            "code {} has an empty meaning",
            e.id
        );
        assert!(
            !e.user_msg.trim().is_empty(),
            "code {} has an empty user_msg",
            e.id
        );
        assert!(
            e.name.chars().all(|c| c.is_ascii_uppercase() || c == '_' || c.is_ascii_digit()),
            "code name {:?} must be SCREAMING_SNAKE_CASE",
            e.name
        );
    }

    let mut rs = String::new();
    rs.push_str("// @generated by build.rs from codes.toml. Do not edit.\n\n");

    // --- enum Code
    rs.push_str("/// A registered Selis error code.\n");
    rs.push_str("///\n");
    rs.push_str("/// Generated from `codes.toml`. A number is never reused and a meaning is\n");
    rs.push_str("/// never changed (03-CONVENTIONS.md §3).\n");
    rs.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]\n");
    rs.push_str("#[non_exhaustive]\n");
    rs.push_str("pub enum Code {\n");
    for e in &registry.code {
        let _ = writeln!(rs, "    /// `{}` — {}", e.id, e.meaning);
        let _ = writeln!(rs, "    {},", pascal(&e.name));
    }
    rs.push_str("}\n\n");

    // --- ALL_CODES
    let _ = writeln!(
        rs,
        "/// Every registered code, ordered by numeric id.\npub static ALL_CODES: [Code; {}] = [",
        registry.code.len()
    );
    let mut sorted: Vec<&Entry> = registry.code.iter().collect();
    sorted.sort_by_key(|e| e.id);
    for e in &sorted {
        let _ = writeln!(rs, "    Code::{},", pascal(&e.name));
    }
    rs.push_str("];\n\n");

    rs.push_str("impl Code {\n");

    // id
    rs.push_str("    /// The stable numeric identifier. Crosses every binding boundary.\n");
    rs.push_str("    #[must_use]\n    pub const fn id(self) -> u32 {\n        match self {\n");
    for e in &registry.code {
        let _ = writeln!(rs, "            Code::{} => {},", pascal(&e.name), e.id);
    }
    rs.push_str("        }\n    }\n\n");

    // name
    rs.push_str("    /// The registry name, e.g. `\"XREF_UNRECOVERABLE\"`.\n");
    rs.push_str("    #[must_use]\n    pub const fn name(self) -> &'static str {\n        match self {\n");
    for e in &registry.code {
        let _ = writeln!(
            rs,
            "            Code::{} => {:?},",
            pascal(&e.name),
            e.name
        );
    }
    rs.push_str("        }\n    }\n\n");

    // kind
    rs.push_str("    /// The broad class of failure.\n");
    rs.push_str("    #[must_use]\n    pub const fn kind(self) -> Kind {\n        match self {\n");
    for e in &registry.code {
        let _ = writeln!(
            rs,
            "            Code::{} => Kind::{},",
            pascal(&e.name),
            e.kind
        );
    }
    rs.push_str("        }\n    }\n\n");

    // doc_state
    rs.push_str("    /// What happened to the user's document. The field that matters\n");
    rs.push_str("    /// (03-CONVENTIONS.md §3, SL-0.ERR.02).\n");
    rs.push_str("    #[must_use]\n    pub const fn doc_state(self) -> DocState {\n        match self {\n");
    for e in &registry.code {
        let _ = writeln!(
            rs,
            "            Code::{} => DocState::{},",
            pascal(&e.name),
            e.doc_state
        );
    }
    rs.push_str("        }\n    }\n\n");

    // retryable
    rs.push_str("    /// Whether retrying the identical operation could plausibly succeed.\n");
    rs.push_str("    #[must_use]\n    pub const fn retryable(self) -> bool {\n        match self {\n");
    for e in &registry.code {
        let _ = writeln!(
            rs,
            "            Code::{} => {},",
            pascal(&e.name),
            e.retryable
        );
    }
    rs.push_str("        }\n    }\n\n");

    // meaning
    rs.push_str("    /// The engineer-facing meaning. Immutable once published.\n");
    rs.push_str("    #[must_use]\n    pub const fn meaning(self) -> &'static str {\n        match self {\n");
    for e in &registry.code {
        let _ = writeln!(
            rs,
            "            Code::{} => {:?},",
            pascal(&e.name),
            e.meaning
        );
    }
    rs.push_str("        }\n    }\n\n");

    // message_key
    rs.push_str("    /// The localisation key for the user-facing message.\n");
    rs.push_str("    ///\n");
    rs.push_str("    /// SL-0.ERR.04: user strings are resolved through this key, never\n");
    rs.push_str("    /// built with `format!`. English is a translation like any other.\n");
    rs.push_str("    #[must_use]\n    pub const fn message_key(self) -> &'static str {\n        match self {\n");
    for e in &registry.code {
        let key = format!("error-{}", e.name.to_lowercase().replace('_', "-"));
        let _ = writeln!(rs, "            Code::{} => {:?},", pascal(&e.name), key);
    }
    rs.push_str("        }\n    }\n\n");

    // user_msg_en
    rs.push_str("    /// The English rendering of [`Code::message_key`].\n");
    rs.push_str("    ///\n");
    rs.push_str("    /// This is the fallback bundle, not a hardcode: a localised build\n");
    rs.push_str("    /// resolves `message_key` against its own catalogue first.\n");
    rs.push_str("    #[must_use]\n    pub const fn user_msg_en(self) -> &'static str {\n        match self {\n");
    for e in &registry.code {
        let _ = writeln!(
            rs,
            "            Code::{} => {:?},",
            pascal(&e.name),
            e.user_msg
        );
    }
    rs.push_str("        }\n    }\n\n");

    // from_id
    rs.push_str("    /// Recover a code from its numeric id, e.g. when crossing back over\n");
    rs.push_str("    /// the C ABI. Returns `None` for an unregistered number.\n");
    rs.push_str("    #[must_use]\n    pub const fn from_id(id: u32) -> Option<Code> {\n        match id {\n");
    for e in &sorted {
        let _ = writeln!(
            rs,
            "            {} => Some(Code::{}),",
            e.id,
            pascal(&e.name)
        );
    }
    rs.push_str("            _ => None,\n        }\n    }\n");
    rs.push_str("}\n");

    let out_rs = std::path::Path::new(&out_dir).join("codes.rs");
    std::fs::write(&out_rs, rs).expect("write codes.rs");

    // --- Markdown reference
    let mut md = String::new();
    md.push_str("# Selis error codes\n\n");
    md.push_str("Generated from `crates/selis-error/codes.toml`. Do not edit.\n\n");
    md.push_str("`doc_state` answers: *what happened to the user's document?*\n\n");
    md.push_str("| Code | Name | Kind | Doc state | Retryable | Meaning | User message |\n");
    md.push_str("|---|---|---|---|---|---|---|\n");
    for e in &sorted {
        let _ = writeln!(
            md,
            "| {} | `{}` | {} | {} | {} | {} | {} |",
            e.id,
            e.name,
            e.kind,
            e.doc_state,
            if e.retryable { "yes" } else { "no" },
            e.meaning.replace('|', "\\|"),
            e.user_msg.replace('|', "\\|")
        );
    }
    let out_md = std::path::Path::new(&out_dir).join("codes.md");
    std::fs::write(&out_md, md).expect("write codes.md");
}
