[package]
name = "selis-error"
description = "Selis error taxonomy and the generated numeric code registry."
edition.workspace = true
rust-version.workspace = true
license = "Apache-2.0"
version.workspace = true
authors.workspace = true
repository.workspace = true

[lints]
workspace = true

[build-dependencies]
toml = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
toml = { workspace = true }
serde = { workspace = true }
