[package]
name = "selis-io"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
selis-error = { workspace = true }
selis-bytes = { workspace = true }

[features]
default = []
native-io = []
