//! SL-1.ENC.03 — the public-key (PKCS#7) security handler, read side:
//! engine-path DoD tests.
//!
//! The committed fixtures under `tests/fixtures/` are generated by
//! `cargo xtask pubkey-fixtures` (deterministic — a fixed RNG seeds the RSA
//! v1.5 padding) and verified against their generator by
//! `cargo xtask pubkey-fixtures --check`. The generator is deliberately
//! independent of `selis-crypto::pkcs7`: it builds the CMS envelopes and
//! derives the file key straight from the spec's Algorithm 1 primitives
//! (SHA-1/SHA-256 of seed ‖ recipients), so the DoD tests cross-check the
//! handler rather than trusting it.
//!
//! Fixtures:
//! * `pubkey-rsa-s4.pdf` — `/V 4` (AESV2, salted per-object keys), RSA-2048
//!   key transport addressed by `issuerAndSerialNumber` (the s4 shape).
//! * `pubkey-ec-s5.pdf` — `/V 5` (AESV3, direct file key), EC P-256 ECDH
//!   key agreement + AES-256-KW inside `/CF /DefaultCryptFilter`, addressed
//!   by `subjectKeyIdentifier` (no cert extension — the identity reader's
//!   method-1 path).
//! * `pubkey-multi-s5.pdf` — `/V 5` with two recipients (EC first, RSA
//!   second) to pin the SL-1.ENC.07 certificate-identity selection (the
//!   RSA credential opens despite *not* being first) and the `match_by`
//!   fall-through semantics.
//! * `pubkey-perms-s5.pdf` — the SL-1.ENC.09 three-recipient file (see
//!   `pubkey_permissions.rs`).
//!
//! The RSA-2048 fixture keypairs are committed next to the fixtures
//! (`enc03-recipient-rsa2048.pk8.der`, `enc03-wrong-rsa2048.pk8.der`) with
//! their self-signed certificates (`*.x509.der`): test-only throwaways,
//! never used for anything real — flagged in the design note for the human
//! sign-off.
#![cfg_attr(
    test,
    allow(
        clippy::unwrap_used,
        clippy::expect_used,
        clippy::panic,
        clippy::indexing_slicing,
        clippy::arithmetic_side_effects,
        clippy::cast_possible_truncation,
        clippy::cast_sign_loss,
        clippy::integer_division
    )
)]

use selis_error::Code;
use selis_pdf_engine::Session;
use selis_sandbox::{Budget, FixedClock, Surface};

// ---------------------------------------------------------------------------
// Committed fixture keys
// ---------------------------------------------------------------------------

/// The recipient RSA-2048 private key (PKCS#8 DER, test-only).
static RECIPIENT_RSA: &[u8] = include_bytes!("fixtures/enc03-recipient-rsa2048.pk8.der");
/// A different RSA-2048 private key that opens nothing (test-only; a
/// legitimate recipient of the `pubkey-perms-s5.pdf` fixture, "Bob").
static WRONG_RSA: &[u8] = include_bytes!("fixtures/enc03-wrong-rsa2048.pk8.der");
/// The recipient EC P-256 private key (PKCS#8 DER, test-only; the fixed
/// scalar the fixtures were built with).
static RECIPIENT_EC: &[u8] = include_bytes!("fixtures/enc03-recipient-ecp256.pk8.der");

// ---------------------------------------------------------------------------
// SL-1.ENC.07: self-signed chains addressing the fixture recipients
// ---------------------------------------------------------------------------

/// The Alice certificate (RSA; the blobs that address her quote its
/// `issuerAndSerialNumber`).
static CERT_RSA: &[u8] = include_bytes!("fixtures/enc03-recipient-rsa2048.x509.der");
/// Bob's certificate (the second RSA key's chain).
static CERT_BOB: &[u8] = include_bytes!("fixtures/enc03-wrong-rsa2048.x509.der");
/// The EC certificate (no SKI extension — its recipients are addressed by
/// the RFC 5280 method-1 SHA-1 of its subject public key).
static CERT_EC: &[u8] = include_bytes!("fixtures/enc03-recipient-ecp256.x509.der");

// ---------------------------------------------------------------------------
// DoD tests
// ---------------------------------------------------------------------------

fn viewer() -> Budget {
    Budget::profile(Surface::Viewer)
}

/// The RSA s4 fixture opens with the recipient private key and the page
/// content decrypts (the display list carries the fill op). A bare key (no
/// chain) selects structurally — the retained fallback of design note §4.
#[test]
fn pubkey_rsa_s4_opens_with_recipient_key() {
    let budget = viewer();
    let credential = selis_crypto::pkcs7::PubKeyCredential::rsa(RECIPIENT_RSA.to_vec());
    let session = Session::open_public_key(
        include_bytes!("fixtures/pubkey-rsa-s4.pdf").to_vec(),
        &credential,
        &budget,
        &FixedClock(0),
    )
    .expect("open with the recipient RSA key");
    assert_eq!(session.len(), 1, "one page");
    assert!(session.page_size(0).is_some(), "page has a media box");
    let receipt = session.recipient_receipt().expect("recipient receipt");
    assert_eq!(
        receipt.matched_by,
        selis_crypto::pkcs7::Matched::Structurally
    );
    assert_eq!(receipt.recipient_index, 0);
    let mut g = budget.guard();
    let dl = session
        .page_display_list(0, &budget, &mut g)
        .expect("display list");
    assert!(!dl.ops.is_empty(), "the decrypted content stream must draw");
}

/// The RSA s4 fixture opens by `issuerWithSerialNumber` identity when the
/// chain is supplied (SL-1.ENC.07 selects the CORRECT recipient by
/// certificate identity first).
#[test]
fn pubkey_rsa_s4_selects_recipient_by_issuer_and_serial() {
    let budget = viewer();
    let credential = selis_crypto::pkcs7::PubKeyCredential::rsa(RECIPIENT_RSA.to_vec())
        .with_certificate(CERT_RSA.to_vec());
    let session = Session::open_public_key(
        include_bytes!("fixtures/pubkey-rsa-s4.pdf").to_vec(),
        &credential,
        &budget,
        &FixedClock(0),
    )
    .expect("identity-first open");
    let receipt = session.recipient_receipt().expect("receipt");
    assert_eq!(
        receipt.matched_by,
        selis_crypto::pkcs7::Matched::ByIssuerAndSerialNumber
    );
}

/// The EC s5 fixture opens with the recipient EC key; with the chain, the
/// blob's `subjectKeyIdentifier` (method-1 — the cert carries no extension)
/// selects the recipient before the unwrap (SL-1.ENC.07).
#[test]
fn pubkey_ec_s5_opens_with_recipient_key() {
    let budget = viewer();
    let credential = selis_crypto::pkcs7::PubKeyCredential::ec_p256(RECIPIENT_EC.to_vec())
        .with_certificate(CERT_EC.to_vec());
    let session = Session::open_public_key(
        include_bytes!("fixtures/pubkey-ec-s5.pdf").to_vec(),
        &credential,
        &budget,
        &FixedClock(0),
    )
    .expect("open with the recipient EC key");
    assert_eq!(session.len(), 1, "one page");
    let receipt = session.recipient_receipt().expect("recipient receipt");
    assert_eq!(
        receipt.matched_by,
        selis_crypto::pkcs7::Matched::BySubjectKeyIdentifier
    );
    let mut g = budget.guard();
    let dl = session
        .page_display_list(0, &budget, &mut g)
        .expect("display list");
    assert!(!dl.ops.is_empty(), "the decrypted content stream must draw");
}

/// The multi-recipient fixture opens for both recipients — each credential
/// with its own chain selects its recipient **by certificate identity
/// first**, whichever side of the array it sits on (SL-1.ENC.07: blob 0 is
/// EC/SKI-addressed, blob 1 is RSA/issuer-serial-addressed).
#[test]
fn pubkey_multi_recipient_matches_each_credential() {
    let budget = viewer();
    let ec = selis_crypto::pkcs7::PubKeyCredential::ec_p256(RECIPIENT_EC.to_vec())
        .with_certificate(CERT_EC.to_vec())
        .matching(selis_crypto::pkcs7::MatchBy::Certificate);
    let session = Session::open_public_key(
        include_bytes!("fixtures/pubkey-multi-s5.pdf").to_vec(),
        &ec,
        &budget,
        &FixedClock(0),
    )
    .expect("the EC recipient opens");
    assert_eq!(session.len(), 1);
    let receipt = session.recipient_receipt().expect("receipt");
    assert_eq!(receipt.recipient_index, 0);
    assert_eq!(
        receipt.matched_by,
        selis_crypto::pkcs7::Matched::BySubjectKeyIdentifier
    );

    let rsa = selis_crypto::pkcs7::PubKeyCredential::rsa(RECIPIENT_RSA.to_vec())
        .with_certificate(CERT_RSA.to_vec())
        .matching(selis_crypto::pkcs7::MatchBy::Certificate);
    let session = Session::open_public_key(
        include_bytes!("fixtures/pubkey-multi-s5.pdf").to_vec(),
        &rsa,
        &budget,
        &FixedClock(0),
    )
    .expect("the RSA recipient opens (identity-first, not array order)");
    assert_eq!(session.len(), 1);
    let receipt = session.recipient_receipt().expect("receipt");
    assert_eq!(receipt.recipient_index, 1);
    assert_eq!(
        receipt.matched_by,
        selis_crypto::pkcs7::Matched::ByIssuerAndSerialNumber
    );
}

/// SL-1.ENC.07 fall-through semantics: a credential whose chain matches no
/// identifier in the blob list still opens under `MatchBy::Auto` when the
/// key material is valid (the structural fall-back), but
/// `MatchBy::Certificate` refuses typed — and never falls back to a
/// differently-addressed recipient.
#[test]
fn pubkey_identity_absent_falls_through_by_match_mode() {
    let budget = viewer();
    // Alice's key presented with Bob's certificate: identity finds nothing
    // in the rsa-s4 blob list (the blob addresses Alice's cert).
    let mismatched = selis_crypto::pkcs7::PubKeyCredential::rsa(RECIPIENT_RSA.to_vec())
        .with_certificate(CERT_BOB.to_vec());
    let session = Session::open_public_key(
        include_bytes!("fixtures/pubkey-rsa-s4.pdf").to_vec(),
        &mismatched,
        &budget,
        &FixedClock(0),
    )
    .expect("auto falls through to the structural first-valid scan");
    assert_eq!(
        session.recipient_receipt().expect("receipt").matched_by,
        selis_crypto::pkcs7::Matched::Structurally
    );

    let strict = mismatched.matching(selis_crypto::pkcs7::MatchBy::Certificate);
    let result = Session::open_public_key(
        include_bytes!("fixtures/pubkey-rsa-s4.pdf").to_vec(),
        &strict,
        &budget,
        &FixedClock(0),
    );
    assert_eq!(
        result.err().map(|e| e.code()),
        Some(Code::RecipientNoMatch),
        "Certificate mode must not open a recipient its chain does not address"
    );

    // A `MatchBy::Certificate` credential with no chain at all matches
    // nothing — typed, even though the key material is valid.
    let no_chain = selis_crypto::pkcs7::PubKeyCredential::rsa(RECIPIENT_RSA.to_vec())
        .matching(selis_crypto::pkcs7::MatchBy::Certificate);
    let result = Session::open_public_key(
        include_bytes!("fixtures/pubkey-rsa-s4.pdf").to_vec(),
        &no_chain,
        &budget,
        &FixedClock(0),
    );
    assert_eq!(result.err().map(|e| e.code()), Some(Code::RecipientNoMatch));
}

/// A wrong key yields the typed `RECIPIENT_NO_MATCH` — never a partial
/// decrypt, never a document opened with a wrong key. The key material must
/// not select a recipient the credential's *identity* addresses (the
/// "duplicate identifier / wrong serial" fuzz invariant, pinned
/// deterministically here).
#[test]
fn pubkey_wrong_key_is_a_typed_error() {
    let budget = viewer();
    let credential = selis_crypto::pkcs7::PubKeyCredential::rsa(WRONG_RSA.to_vec());
    let result = Session::open_public_key(
        include_bytes!("fixtures/pubkey-rsa-s4.pdf").to_vec(),
        &credential,
        &budget,
        &FixedClock(0),
    );
    match result {
        Err(e) => assert_eq!(e.code(), Code::RecipientNoMatch),
        Ok(_) => panic!("the wrong key must not open the document"),
    }

    // The wrong key also fails against the multi-recipient fixture (both
    // transports refused) in every selection mode (auto / first_valid /
    // certificate).
    for mode in [
        selis_crypto::pkcs7::MatchBy::Auto,
        selis_crypto::pkcs7::MatchBy::FirstValid,
        selis_crypto::pkcs7::MatchBy::Certificate,
    ] {
        let credential = selis_crypto::pkcs7::PubKeyCredential::rsa(WRONG_RSA.to_vec())
            .with_certificate(CERT_BOB.to_vec())
            .matching(mode);
        let result = Session::open_public_key(
            include_bytes!("fixtures/pubkey-multi-s5.pdf").to_vec(),
            &credential,
            &budget,
            &FixedClock(0),
        );
        match result {
            Err(e) => assert_eq!(e.code(), Code::RecipientNoMatch, "mode {mode:?}"),
            Ok(_) => panic!("the wrong key must not open the multi fixture (mode {mode:?})"),
        }
    }
}

/// Without a credential, a public-key document opens tolerantly (the
/// established Session::open posture) — structurally, without decrypted
/// content.
#[test]
fn pubkey_without_credential_opens_tolerantly() {
    let budget = viewer();
    let session = Session::open(
        include_bytes!("fixtures/pubkey-rsa-s4.pdf").to_vec(),
        &budget,
        &FixedClock(0),
    )
    .expect("tolerant open without a credential");
    assert_eq!(session.len(), 1, "the page tree is plaintext");
    assert!(
        session.recipient_receipt().is_none(),
        "a credential-less open carries no recipient receipt"
    );
}
