//! SL-1.ENC.03 — the public-key (PKCS#7) security handler, read side:
//! engine-path DoD tests.
//!
//! The three committed fixtures under `tests/fixtures/` are generated by
//! `cargo xtask pubkey-fixtures` (deterministic — a fixed RNG seeds the RSA
//! v1.5 padding) and verified against their generator by
//! `cargo xtask pubkey-fixtures --check`. The generator is deliberately
//! independent of `selis-crypto::pkcs7`: it builds the CMS envelopes and
//! derives the file key straight from the spec's Algorithm 1 primitives
//! (SHA-1/SHA-256 of seed ‖ recipients), so the DoD tests cross-check the
//! handler instead of trusting it.
//!
//! Fixtures:
//! * `pubkey-rsa-s4.pdf` — `/V 4` (AESV2, salted per-object keys), RSA-2048
//!   key transport, `/Recipients` directly on the `/Encrypt` dictionary
//!   (the s4 shape).
//! * `pubkey-ec-s5.pdf` — `/V 5` (AESV3, direct file key), EC P-256 ECDH
//!   key agreement + AES-256-KW inside `/CF /DefaultCryptFilter`
//!   (Acrobat's s5 shape).
//! * `pubkey-multi-s5.pdf` — `/V 5` with two recipients (EC first, RSA
//!   second) to pin the first-match credential-selection policy.
//!
//! The RSA-2048 fixture keypairs are committed next to the fixtures
//! (`enc03-recipient-rsa2048.pk8.der`, `enc03-wrong-rsa2048.pk8.der`):
//! test-only throwaway keys, never used for anything real — flagged in the
//! design note for the human sign-off.
#![cfg_attr(
    test,
    allow(
        clippy::unwrap_used,
        clippy::expect_used,
        clippy::panic,
        clippy::indexing_slicing,
        clippy::arithmetic_side_effects,
        clippy::cast_possible_truncation,
        clippy::cast_sign_loss,
        clippy::integer_division
    )
)]

use selis_error::Code;
use selis_pdf_engine::Session;
use selis_sandbox::{Budget, FixedClock, Surface};

// ---------------------------------------------------------------------------
// Committed fixture keys
// ---------------------------------------------------------------------------

/// The recipient RSA-2048 private key (PKCS#8 DER, test-only).
static RECIPIENT_RSA: &[u8] = include_bytes!("fixtures/enc03-recipient-rsa2048.pk8.der");
/// A different RSA-2048 private key that opens nothing (test-only).
static WRONG_RSA: &[u8] = include_bytes!("fixtures/enc03-wrong-rsa2048.pk8.der");
/// The recipient EC P-256 private key (PKCS#8 DER, test-only; the fixed
/// scalar the fixtures were built with).
static RECIPIENT_EC: &[u8] = include_bytes!("fixtures/enc03-recipient-ecp256.pk8.der");

// ---------------------------------------------------------------------------
// DoD tests
// ---------------------------------------------------------------------------

fn viewer() -> Budget {
    Budget::profile(Surface::Viewer)
}

/// The RSA s4 fixture opens with the recipient private key and the page
/// content decrypts (the display list carries the fill op).
#[test]
fn pubkey_rsa_s4_opens_with_recipient_key() {
    let budget = viewer();
    let credential = selis_crypto::pkcs7::PubKeyCredential::Rsa(RECIPIENT_RSA.to_vec());
    let session = Session::open_public_key(
        include_bytes!("fixtures/pubkey-rsa-s4.pdf").to_vec(),
        &credential,
        &budget,
        &FixedClock(0),
    )
    .expect("open with the recipient RSA key");
    assert_eq!(session.len(), 1, "one page");
    assert!(session.page_size(0).is_some(), "page has a media box");
    let mut g = budget.guard();
    let dl = session
        .page_display_list(0, &budget, &mut g)
        .expect("display list");
    assert!(!dl.ops.is_empty(), "the decrypted content stream must draw");
}

/// The EC s5 fixture opens with the recipient EC key.
#[test]
fn pubkey_ec_s5_opens_with_recipient_key() {
    let budget = viewer();
    let credential = selis_crypto::pkcs7::PubKeyCredential::EcP256(RECIPIENT_EC.to_vec());
    let session = Session::open_public_key(
        include_bytes!("fixtures/pubkey-ec-s5.pdf").to_vec(),
        &credential,
        &budget,
        &FixedClock(0),
    )
    .expect("open with the recipient EC key");
    assert_eq!(session.len(), 1, "one page");
    let mut g = budget.guard();
    let dl = session
        .page_display_list(0, &budget, &mut g)
        .expect("display list");
    assert!(!dl.ops.is_empty(), "the decrypted content stream must draw");
}

/// The multi-recipient fixture opens for both recipients — the EC blob is
/// first, so the RSA credential must skip it (wrong transport type) and
/// match the second entry (first-match policy, design note §4).
#[test]
fn pubkey_multi_recipient_matches_each_credential() {
    let budget = viewer();
    let ec = selis_crypto::pkcs7::PubKeyCredential::EcP256(RECIPIENT_EC.to_vec());
    let session = Session::open_public_key(
        include_bytes!("fixtures/pubkey-multi-s5.pdf").to_vec(),
        &ec,
        &budget,
        &FixedClock(0),
    )
    .expect("the EC recipient opens");
    assert_eq!(session.len(), 1);

    let rsa = selis_crypto::pkcs7::PubKeyCredential::Rsa(RECIPIENT_RSA.to_vec());
    let session = Session::open_public_key(
        include_bytes!("fixtures/pubkey-multi-s5.pdf").to_vec(),
        &rsa,
        &budget,
        &FixedClock(0),
    )
    .expect("the RSA recipient opens (skipping the EC blob)");
    assert_eq!(session.len(), 1);
}

/// A wrong key yields the typed `RECIPIENT_NO_MATCH` — never a partial
/// decrypt, never a document opened with a wrong key.
#[test]
fn pubkey_wrong_key_is_a_typed_error() {
    let budget = viewer();
    let credential = selis_crypto::pkcs7::PubKeyCredential::Rsa(WRONG_RSA.to_vec());
    let result = Session::open_public_key(
        include_bytes!("fixtures/pubkey-rsa-s4.pdf").to_vec(),
        &credential,
        &budget,
        &FixedClock(0),
    );
    match result {
        Err(e) => assert_eq!(e.code(), Code::RecipientNoMatch),
        Ok(_) => panic!("the wrong key must not open the document"),
    }

    // The wrong key also fails against the multi-recipient fixture (both
    // transports refused).
    let result = Session::open_public_key(
        include_bytes!("fixtures/pubkey-multi-s5.pdf").to_vec(),
        &credential,
        &budget,
        &FixedClock(0),
    );
    match result {
        Err(e) => assert_eq!(e.code(), Code::RecipientNoMatch),
        Ok(_) => panic!("the wrong key must not open the multi fixture"),
    }
}

/// Without a credential, a public-key document opens tolerantly (the
/// established Session::open posture) — structurally, without decrypted
/// content.
#[test]
fn pubkey_without_credential_opens_tolerantly() {
    let budget = viewer();
    let session = Session::open(
        include_bytes!("fixtures/pubkey-rsa-s4.pdf").to_vec(),
        &budget,
        &FixedClock(0),
    )
    .expect("tolerant open without a credential");
    assert_eq!(session.len(), 1, "the page tree is plaintext");
}
